set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[0]}]
set_property PACKAGE_PIN J14 [get_ports {leds_tri_o[0]}]
set_property PACKAGE_PIN K14 [get_ports {leds_tri_o[1]}]
set_property PACKAGE_PIN J18 [get_ports {leds_tri_o[2]}]
set_property PACKAGE_PIN H18 [get_ports {leds_tri_o[3]}]