set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[0]}]
set_property PACKAGE_PIN M15 [get_ports {btns_tri_i[0]}]
set_property PACKAGE_PIN M14 [get_ports {btns_tri_i[1]}]
set_property PACKAGE_PIN L17 [get_ports {btns_tri_i[2]}]
set_property PACKAGE_PIN L16 [get_ports {btns_tri_i[3]}]